### ISSUE TITLE
.extend() doesnt work any more

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/radiospectra#2]
the standard command from the doc does not work

just type:

more = image.extend()

**Comment by Beckicious** [comment]
The following code worked for me:

```
from radiospectra.sources import CallistoSpectrogram
image = CallistoSpectrogram.from_range('ALASKA', '2018-04-01 00:00:00', '2018-04-01 00:15:00')
image.peek()
more = image.extend()
more.peek()
```

Could you test if that code works for you? I've put it into a [notebook](https://github.com/i4Ds/radiospectra/tree/master/examples/test_extend.ipynb).

**Comment by ACsillaghy** [comment]
mmm yes this worked. Does the standard work for you?

import matplotlib.pyplot as plt
import sunpy.data.sample
image = CallistoSpectrogram.read(sunpy.data.sample.CALLISTO_SPECTRUM)
image.peek()
more = image.extend()
more.peek()

?
