### ISSUE TITLE
Von wo kommt im Path dieses falsche dir von David Sommer? 

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/radiospectra#7]
es kommt nicht wenn ich ohne radiospectra starte.

print( sys.path )

['/Users/csillag/anaconda3/lib/python36.zip', '/Users/csillag/pCloud Drive/GitHub/radiospectra', 'C:\\Users\\David Sommer\\Documents\\GitHub\\radiospectra', '/Users/csillag/pCloud Drive/GitHub/radiospectra', '/Users/csillag/anaconda3/lib/python3.6', '/Users/csillag/anaconda3/lib/python3.6/lib-dynload', '', '/Users/csillag/.local/lib/python3.6/site-packages', '/Users/csillag/anaconda3/lib/python3.6/site-packages', '/Users/csillag/anaconda3/lib/python3.6/site-packages/aeosa', '/Users/csillag/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/Users/csillag/.ipython']

**Comment by Beckicious** [comment]
These lines were wrongly added in c6240525eb69a2a0d91da6130d599f74b0ec0b7e:

![image](https://user-images.githubusercontent.com/14994259/61993119-478c2e00-b067-11e9-99f1-0550466c9188.png)
