### ISSUE TITLE
Missing axes leads to wrong calculation of the freq_axis in callisto.py (IndexError: index 199 is out of bounds for axis 0 with size 50)

### ISSUE THREAD

**Issue by SyleKu** [i4Ds/radiospectra#8]
When trying to do a background subtraction of the "**_GAURI_20131012_040020_59.fit_**" fits file, which has no axes in the file, it first leads to a "**_IndexError: list index out of range_**" Error.

**This can easily be solved by adding these codes:**

**try except for the axes:**

![grafik](https://user-images.githubusercontent.com/5213937/109232556-c8be2080-77c8-11eb-990c-e56f45b8900f.png)

**And setting None before the axes check for tm and fq:**

![grafik](https://user-images.githubusercontent.com/5213937/109232919-4eda6700-77c9-11eb-825e-12d0ef282561.png)

After adding these missing codes it leads to the situation where **tm** and **fq** are **None** and it will try to calculate **freq_axis** (see line 334):

![grafik](https://user-images.githubusercontent.com/5213937/109233078-86e1aa00-77c9-11eb-8039-00c7754b9144.png)

The error occurs on line 341, where it tries to access an index in **freq_axis** which doesn't exist, since the array length is too small (here the array length of **freq_axis** would be 50) and the value of **right** is 199:

![grafik](https://user-images.githubusercontent.com/5213937/109233346-07a0a600-77ca-11eb-9ac3-880008dcb073.png)

**Error message:**

![grafik](https://user-images.githubusercontent.com/5213937/109233378-171fef00-77ca-11eb-8bd1-bedc57eb32a3.png)

@Beckicious:
Do you have any idea on how to solve this?

**Note:**
I am using the radiospectra master branch for running the background subtraction.

**Comment by Beckicious** [comment]
Do we have to be able to work with CallistoSpectrograms that have no time or frequency axis?

**Comment by ACsillaghy** [comment]
I think there is some confusion about the axes. There are different ways to specify the axes. But to answer the question of Simon: I think there should always be an axis. The axis is either in one of the binary tables, or it should be constructed from the header information (and thus assumed to have equidistant values).

**Comment by SyleKu** [comment]
When you check out  the "_**GAURI_20131012_040020_59.fit**_" fits file, you will only see these information (since it doesn't have a second table for the frequencies):

![grafik](https://user-images.githubusercontent.com/5213937/110594175-c2428800-817c-11eb-9efd-3801cb62952b.png)

I am not quite sure if we are able to construct the information about the frequencies (probably not), but we have the information about the time axis for sure.


Actually when checking out the callistoQuicklook images (http://soleil.i4ds.ch/solarradio/callistoQuicklooks/?date=20131012) we  don't have an image there, so we really can skip fits files which doesn't have axis at all.

![grafik](https://user-images.githubusercontent.com/5213937/110591153-fddb5300-8178-11eb-8b28-9ebe1b3a3a6c.png)


However, I would still suggest to put the `try except` clause around the "`axes = fl[1]`" code as I did in the first image but with the error information such as "_Warning: Your provided fits file doesn't have axis information_" (or something like that) just to keep the code clean, otherwise threads would crash at this point, since no exception is thrown there.

Currently the "**_callisto.py_**" file looks like this:

![grafik](https://user-images.githubusercontent.com/5213937/110593360-c1f5bd00-817b-11eb-8dc3-f7cf383c704b.png)

**Comment by ACsillaghy** [comment]
Dear Kushtrim

Did you check the contents of this file? Yes if there is no main array then it is pointless. But if you have an array and you have the frequency information in the header, then you should construct the axis based on this information.

Herzliche Grüsse
André

----
Tel +41 76 330 2049 / Zoom 841 949 8036<https://fhnw.zoom.us/j/8419498036>
